# Generated by Django 5.2.3 on 2025-06-22 11:39

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightLossCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('min_weight_loss', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum Kilo Kaybı')),
                ('max_weight_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Maksimum Kilo Kaybı')),
                ('color', models.CharField(default='#28a745', max_length=7, verbose_name='Renk')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Kilo Kaybı Kategorisi',
                'verbose_name_plural': 'Kilo Kaybı Kategorileri',
                'ordering': ['min_weight_loss'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('age_range', models.CharField(choices=[('18-25', '18-25 yaş'), ('26-35', '26-35 yaş'), ('36-45', '36-45 yaş'), ('46-55', '46-55 yaş'), ('56+', '56+ yaş')], max_length=10, verbose_name='Yaş Aralığı')),
                ('gender', models.CharField(choices=[('male', 'Erkek'), ('female', 'Kadın')], max_length=10, verbose_name='Cinsiyet')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Meslek')),
                ('initial_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Başlangıç Kilosu (kg)')),
                ('final_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Son Kilo (kg)')),
                ('weight_lost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Verilen Kilo (kg)')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Süre (ay)')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('summary', models.TextField(verbose_name='Özet')),
                ('story_content', ckeditor.fields.RichTextField(verbose_name='Hikaye İçeriği')),
                ('before_image', models.ImageField(upload_to='success_stories/before/', verbose_name='Öncesi Resmi')),
                ('after_image', models.ImageField(upload_to='success_stories/after/', verbose_name='Sonrası Resmi')),
                ('profile_image', models.ImageField(blank=True, upload_to='success_stories/profiles/', verbose_name='Profil Resmi')),
                ('initial_goals', models.TextField(verbose_name='Başlangıç Hedefleri')),
                ('challenges_faced', models.TextField(blank=True, verbose_name='Karşılaştığı Zorluklar')),
                ('key_changes', models.TextField(verbose_name='Yapılan Ana Değişiklikler')),
                ('client_testimonial', models.TextField(verbose_name='Müşteri Yorumu')),
                ('health_improvements', models.TextField(blank=True, verbose_name='Sağlık İyileştirmeleri')),
                ('lifestyle_changes', models.TextField(blank=True, verbose_name='Yaşam Tarzı Değişiklikleri')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayınlanmış')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Yorum Kabul Et')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('success_date', models.DateField(verbose_name='Başarı Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Başarı Hikayesi',
                'verbose_name_plural': 'Başarı Hikayeleri',
                'ordering': ['-success_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BeforeAfterComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Göğüs (cm) - Öncesi')),
                ('before_waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bel (cm) - Öncesi')),
                ('before_hip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kalça (cm) - Öncesi')),
                ('after_chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Göğüs (cm) - Sonrası')),
                ('after_waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bel (cm) - Sonrası')),
                ('after_hip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Kalça (cm) - Sonrası')),
                ('before_bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='BMI - Öncesi')),
                ('after_bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='BMI - Sonrası')),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='success_stories.successstory')),
            ],
            options={
                'verbose_name': 'Önce-Sonra Karşılaştırması',
                'verbose_name_plural': 'Önce-Sonra Karşılaştırmaları',
            },
        ),
        migrations.CreateModel(
            name='SuccessStoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylanmış')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='success_stories.successstory')),
            ],
            options={
                'verbose_name': 'Hikaye Yorumu',
                'verbose_name_plural': 'Hikaye Yorumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
