# Generated by Django 5.2.3 on 2025-06-22 11:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_days_ahead', models.PositiveIntegerField(default=30, verbose_name='Kaç gün öncesinden randevu alınabilir')),
                ('min_hours_ahead', models.PositiveIntegerField(default=24, verbose_name='Kaç saat öncesinden randevu alınabilir')),
                ('working_days', models.CharField(default='1,2,3,4,5', help_text='1=Pazartesi, 2=Salı, ... 7=Pazar', max_length=50, verbose_name='Çalışma Günleri')),
            ],
            options={
                'verbose_name': 'Randevu Ayarları',
                'verbose_name_plural': 'Randevu Ayarları',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Randevu Saati',
                'verbose_name_plural': 'Randevu Saatleri',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon numarası '+999999999' formatında olmalıdır.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon')),
                ('appointment_date', models.DateField(verbose_name='Randevu Tarihi')),
                ('appointment_type', models.CharField(choices=[('first_consultation', 'İlk Konsültasyon'), ('follow_up', 'Kontrol Randevusu'), ('online', 'Online Görüşme'), ('group_session', 'Grup Seansı')], default='first_consultation', max_length=20, verbose_name='Randevu Türü')),
                ('age', models.PositiveIntegerField(verbose_name='Yaş')),
                ('gender', models.CharField(choices=[('male', 'Erkek'), ('female', 'Kadın')], max_length=10, verbose_name='Cinsiyet')),
                ('height', models.PositiveIntegerField(verbose_name='Boy (cm)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kilo (kg)')),
                ('medical_history', models.TextField(blank=True, help_text='Kronik hastalıklar, alerji vb.', verbose_name='Medikal Geçmiş')),
                ('medications', models.TextField(blank=True, verbose_name='Kullandığı İlaçlar')),
                ('dietary_restrictions', models.TextField(blank=True, verbose_name='Beslenme Kısıtlamaları')),
                ('goals', models.TextField(verbose_name='Hedefler')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('confirmed', 'Onaylandı'), ('cancelled', 'İptal Edildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.timeslot', verbose_name='Randevu Saati')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['-appointment_date', '-appointment_time__time'],
                'unique_together': {('appointment_date', 'appointment_time')},
            },
        ),
    ]
