# Generated by Django 5.2.3 on 2025-06-22 11:39

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('color', models.CharField(default='#007bff', help_text='Hex renk kodu (#ffffff)', max_length=7, verbose_name='Renk')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarif Kategorisi',
                'verbose_name_plural': 'Tarif Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tarif Adı')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Kısa Açıklama')),
                ('image', models.ImageField(upload_to='recipes/', verbose_name='Ana Resim')),
                ('ingredients', ckeditor.fields.RichTextField(verbose_name='Malzemeler')),
                ('instructions', ckeditor.fields.RichTextField(verbose_name='Yapılışı')),
                ('prep_time', models.PositiveIntegerField(verbose_name='Hazırlık Süresi (dakika)')),
                ('cook_time', models.PositiveIntegerField(verbose_name='Pişirme Süresi (dakika)')),
                ('servings', models.PositiveIntegerField(verbose_name='Kaç Kişilik')),
                ('difficulty', models.CharField(choices=[('easy', 'Kolay'), ('medium', 'Orta'), ('hard', 'Zor')], default='easy', max_length=10, verbose_name='Zorluk')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Kahvaltı'), ('lunch', 'Öğle Yemeği'), ('dinner', 'Akşam Yemeği'), ('snack', 'Atıştırmalık'), ('dessert', 'Tatlı'), ('drink', 'İçecek')], max_length=15, verbose_name='Öğün Türü')),
                ('calories_per_serving', models.PositiveIntegerField(blank=True, null=True, verbose_name='Porsiyon Başı Kalori')),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Protein (g)')),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Karbonhidrat (g)')),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Yağ (g)')),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lif (g)')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayırın (ör: vegan, glutensiz, düşük kalorili)', max_length=300, verbose_name='Etiketler')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vejetaryen')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Vegan')),
                ('is_gluten_free', models.BooleanField(default=False, verbose_name='Glutensiz')),
                ('is_low_carb', models.BooleanField(default=False, verbose_name='Düşük Karbonhidratlı')),
                ('is_high_protein', models.BooleanField(default=False, verbose_name='Yüksek Proteinli')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayınlanmış')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipecategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Tarif Resmi',
                'verbose_name_plural': 'Tarif Resimleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Puan')),
                ('comment', models.TextField(blank=True, verbose_name='Yorum')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylanmış')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Tarif Değerlendirmesi',
                'verbose_name_plural': 'Tarif Değerlendirmeleri',
                'ordering': ['-created_at'],
                'unique_together': {('recipe', 'email')},
            },
        ),
    ]
